version: '3.8'
services:
  postgres:
    container_name: postgres_bft
    image: postgres:15.1
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DBNAME} -U ${PG_USER}"]
      interval: 1s
      timeout: 1s
      retries: 5
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  django:
    container_name: django_bft
    build: .
    env_file: .env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
