version: '3.9'
services:
  postgres:
    container_name: sirius_access
    image: postgres:15.1
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DBNAME} -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped